### ISSUE TITLE
Debounce keypad

### ISSUE THREAD

**Issue by kaamburoow** [octopuslab-cz/micropython-keypad#1]
The keypad isn't debounced. If I hold a digit it would keep printing that digit.

**Comment by petrkr** [comment]
Actually it is debounced
https://github.com/octopuslab-cz/micropython-keypad/blob/b2556efe146247c8bf1823809591c0c6641f0897/keypad/__init__.py#L47

What you mention is 'repeate', same if you keep key on PC keyboard, it also repeating that key.

Only difference is, I do not have here that 1st longer delay before repeate occurs

**Comment by kaamburoow** [comment]
How would I remove that repeating?

**Comment by petrkr** [comment]
Function for disable repeating is not implemented.

If you want to help with implementation, it would be nice to make that in that init file in get_key, where will be logic, if is disabled auto repeate, it will wait for key release (or key change) even you can press more keys at once, but only first is taken. Multipress can be implemented aswell, but that was not needed in any project yet.

**Comment by kaamburoow** [comment]
@petrkr Fixed multiple keypresses and repeating, opened a pull request.
